spring:
  application:
    name: Agenda de contactos
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schedulecontacts
    username: root
    password: 19970607
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true



